apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "configmap.labels" . | nindent 4 }}
data:
  envoy.yaml: |-
    {{- .Files.Get "envoy.yaml" | nindent 4 }}
