apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "secret.labels" . | nindent 4 }}
type: Opaque
stringData:
  policy.rego: |-
    {{- .Files.Get "policy.rego" | nindent 4 }}