version: "3.8"

services:
  front-web:
    image: front-web:v1
    container_name: front-web
    build:
      context: frontend
    depends_on:
      - front-envoy
      - user-service
      - product-service
    volumes:
      - ./frontend:/usr/src/app:rw
      - /usr/src/app/node_modules
    networks:
      - envoymesh
    ports:
      - "3000:3000"

  front-envoy:
    image: front-envoy:v1
    container_name: front-envoy
    build:
      context: ./envoy
      dockerfile: Dockerfile
    environment:
      - FRONT_ENVOY_YAML
      - DEBUG_LOG
    networks:
      - envoymesh
    ports:
      - "9901:9901"
      - "8000:8000"

  user-service:
    image: user-service:v1
    container_name: user-service
    build:
      context: ./backend
      dockerfile: user-service/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - envoymesh

  product-service:
    image: product-service:v1
    container_name: product-service
    build:
      context: ./backend
      dockerfile: product-service/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - envoymesh

  opa-service:
    image: openpolicyagent/opa:latest-envoy
    container_name: opa-service
    volumes:
      - ./config/opa-polices/policy.rego:/etc/policy.rego
    command:
      - run
      - --log-level=debug
      - --server
      - --log-format=json-pretty
      - --addr=:8181
      - --set=plugins.envoy_ext_authz_grpc.addr=:9002
      - --set=decision_logs.console=true
      - /etc/policy.rego
    ports:
      - "8181:8181"
    networks:
      - envoymesh

networks:
  envoymesh: {}
